config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { sessions: "user/sessions", registration: "user/registrations" }

  root 'profiles#index'

  resources :users do
		resources :groups do
      resources :subscriptions, only: [:create]
    end
    resources :profiles
    resources :walls, only: [:show] do
      resources :posts, only: [:create, :show] do
        resources :comments, only: [:create, :index]
      end
    end
    resources :friendships, only: [:create, :destroy]
    resources :feed_histories, only: [:show]
  end

  resources :groups, only: [:show, :destroy]
  resources :tags, only: [:index]

  patch 'friendships/read_requests' => 'friendships#read_requests'
  patch 'friendships/accept_friendship/:id' => 'friendships#accept_friendship'
  patch 'friendships/decline_friendship/:id' => 'friendships#decline_friendship'
  patch 'notifications/read_notifications/' => 'notifications#read_notifications'
  post  'posts/like' => 'posts#like'
  post  'comments/like' => 'comments#like'
  get 'comments/check_for_like' => 'comments#check_for_like'
  get 'users/:user_id/feed_histories/:id/sort_by_date' => 'feed_histories#sort_by_date'
  get 'users/:user_id/feed_histories/:id/sort_by_recommended' => 'feed_histories#sort_by_recommended'
  delete 'users/:user_id/groups/:group_id/subscriptions' => 'subscriptions#delete', as: :destroy_subscription

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates :text, length: { minimum: 2 }
  belongs_to :user
  belongs_to :post
  has_many :user_likes_posts, :as => :likeable
  has_many :users, :through => :user_likes_posts
  has_one :notification, :as => :notifiable
end

app/models/feed.rb
class Feed < ActiveRecord::Base
  belongs_to :user
  has_one :feed_history

  accepts_nested_attributes_for :feed_history,
    :reject_if => :all_blank,
    :allow_destroy => true
end

app/models/feed_history.rb
class FeedHistory < ActiveRecord::Base
  belongs_to :feed
  has_many :feed_history_has_posts
  has_many :posts, through: :feed_history_has_posts
end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
  belongs_to :user
  belongs_to :friend, :class_name => "User"
end

app/models/group.rb
class Group < ActiveRecord::Base
	belongs_to :admin, class_name: 'User'
	has_many :subscriptions
	has_many :users, :through => :subscriptions
	has_one :wall, as: :walled
  
  has_many :groups_have_tags
  has_many :tags, :through => :groups_have_tags
end

app/models/groups_have_tag.rb
class GroupsHaveTag < ActiveRecord::Base
  belongs_to :group
  belongs_to :tag
end

app/models/notification.rb
class Notification < ActiveRecord::Base
  belongs_to :user
  belongs_to :actor, :class_name => "User"
  belongs_to :notifiable, polymorphic: true
  #  Notification.create(:user_id => 13, :actor_id => 12, :notifiable_id => 7, :notifiable_type => 'Post', :message_type => 0, :seen => false)
end

app/models/post.rb
class Post < ActiveRecord::Base
  validates :text, length: { minimum: 2 }
  belongs_to :wall
  belongs_to :user
  has_many :feed_history_has_posts
  has_many :feed_histories, through: :feed_history_has_post
  has_many :comments
  has_many :user_likes_posts, :as => :likeable
  has_many :users, :through => :user_likes_posts
  has_one :notification, :as => :notifiable
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
  mount_uploader :avatar, AvatarUploader
  validates :first_name, presence: true
  validates :last_name, presence: true
end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
	belongs_to :user
	belongs_to :group
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :groups_have_tags
  has_many :groups, :through => :groups_have_tags
	
	has_many :user_interests
	has_many :users, :through => :user_interests
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  has_one :wall, as: :walled
  has_many :posts
  has_one :profile
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
  has_many :friendships
  has_many :friends, :through => :friendships
  has_many :user_likes_posts
  has_many :post_likes, :through => :user_likes_posts, :source => :likeable, :source_type => 'Post'
  has_many :comment_likes, :through => :user_likes_posts, :source => :likeable, :source_type => 'Comment'
  has_many :inverse_friendships, :class_name => "Friendship", :foreign_key => "friend_id"
  has_many :inverse_friends, :through => :inverse_friendships, :source => :user
  has_one :feed
  has_one :feed_history, through: :feed
  has_many :comments
  has_one :notification
  has_one :user_friends_preferences
	
	has_many :owned_groups, foreign_key: :admin_id, class_name: 'Group'
	has_many :subscriptions
	has_many :groups, :through => :subscriptions
	
	has_many :user_interests
	has_many :tags, :through => :user_interests
	

  accepts_nested_attributes_for :feed_history,
    :reject_if => :all_blank,
    :allow_destroy => true
end

app/models/user_interest.rb
class UserInterest < ActiveRecord::Base
  belongs_to :user
  belongs_to :tag
end

app/models/user_likes_post.rb
class UserLikesPost < ActiveRecord::Base
  belongs_to :user
  belongs_to :likeable, :polymorphic => true
end

app/models/user_popularity.rb
class UserPopularity < ActiveRecord::Base
  belongs_to :user
end

app/models/wall.rb
class Wall < ActiveRecord::Base
  has_many :posts
  belongs_to :walled, polymorphic: true
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  respond_to :json

	def index
		@groups = current_user.groups

		groupAux = Array.new
		current_user.tags.each do |tag|
			groupAux += tag.groups
		end

		groupAux2 = groupAux.uniq
		groupAux3 = groupAux2.sort { |a, b| a.users.count <=> b.users.count }
		@recGroups = groupAux3.reverse

    @recGroups.each do |group|
      if Subscription.exists?(:user_id => current_user.id, :group_id => group.id)
        @recGroups.delete(group)
      end
    end

	end

  def new
  end

  def show
    @group = Group.find(params[:id])
    @posts = @group.wall.posts
    @hasSubscribed = Subscription.exists?(group_id: params[:id], user_id: current_user.id)

  end

  def create


    @cats = params[:categories]

    @newGroup = Group.new
    @newGroup.title = params[:title]
    @newGroup.description = params[:description]
    @newGroup.admin_id = params[:user_id]
    @newGroup.imageSource = params[:imageSource]
		shortDesc = params[:description].slice(0..10)
		shortDesc = shortDesc + '...'
		@newGroup.short_description = shortDesc

    @cats.each do |cat|
      @newGroup.tags << Tag.find(cat[:id])
    end

    if @newGroup.save
      @newGroup.users << @newGroup.admin
      @newGroup.wall = Wall.create()
      render :json => { :redirect_to => "/groups/" + @newGroup.id.to_s }
    else
      render :json => { :redirect_to => ''}
    end

  end


	def destroy
		@entries = Subscription.where(:group_id => params[:id])
		@entries.find_each do |entry|
			entry.destroy
		end

		GroupsHaveTag.where(:group_id => params[:id]).find_each do |entry|
			entry.destroy
		end

		Group.find(params[:id]).wall.posts.find_each do |post|
      Notification.where(:notifiable_type => 'Post', :notifiable_id => post.id).destroy_all
      post.comments.each do |comment|
        Notification.where(:notifiable_type => 'Comment', :notifiable_id => comment.id).destroy_all
        comment.destroy
      end
		end

		Group.find(params[:id]).wall.posts.destroy_all

		Group.find(params[:id]).wall.destroy

		Group.find(params[:id]).destroy


		redirect_to  user_groups_path(current_user.id)
	end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/walls_helper.rb
module WallsHelper
end

app/views/groups/index.html.haml
.container-fluid
  .row.feed_title
    .col-md-4
    .col-md-4.profile_title
      %h2 Your Groups
    .col-md-2
    .col-md-2
      =button_to "Create group", new_user_group_path(current_user.id), :class => "btn btn-default", :method => :get
  %br
  .row
    .col-md-7
      .row
        .col-md-2
        .col-md-7.profile_title
          .row
            .col-md-12
              %h2.group_subtitle Subscribed groups

              -if @groups.blank?
                .alert.alert-warning You are not subscribed to any groups
              -else
                - @groups.each do |group|
                  = render("layouts/group.html.haml", :group => group)
        .col-md-3
    .col-md-4
      .row
        .col-md-12.profile_title
          %h2.group_subtitle Recommended
          .row
            .col-md-12
              -if @recGroups.blank?
                .alert.alert-warning We do not have any recommended groups for you yet
              - else
                - @recGroups.each do |group|
                  = render("layouts/group.html.haml", :group => group)

app/views/groups/new.html.haml
.container-fluid
  .row.feed_title
    .col-md-4
    .col-md-4.profile_title
      %h2 Create group
    .col-md-4
  %br

  .row
    .col-md-2
    .col-md-8
      = react_component('GroupCreationView', {user_id: params[:user_id]})
    .col-md-2

app/views/groups/show.html.haml
.row.feed_title
  .col-md-2
  .col-md-6
    .media
      .media-left.media-middle
        .a{:href => "#"}
          %img.media-object{:src => @group.imageSource, :witdh => 64, :height => 64 }
      .media-body
        %h2.media-heading
          = @group.title
        %p
          = @group.description
  .col-md-2
    - if @hasSubscribed
      .btn.btn-primary{ 'data-toggle' => 'modal', 'data-target' => '#myModal'} Post
    - else
      = link_to "Subscribe", user_group_subscriptions_path(current_user.id, @group.id), :method => :post, :remote => true, :class => "btn btn-primary"
  .col-md-2
    - if @group.admin_id == current_user.id
      = link_to "Delete Group", user_group_path(current_user.id, @group.id), :method => :delete, :remote => true, :class => "btn btn-default"
    - else
      - if @hasSubscribed
        = link_to "Unsubscribe", destroy_subscription_path(current_user.id, @group.id), :method => :delete, :remote => true, :class => "btn btn-default"
%br

- if @hasSubscribed
  - unless @posts.blank?
    - @posts.each do |post|
      = render "layouts/post", :post => post
  - else
    .alert.alert-info No one has posted here yet! Be the first

  .modal.fade#myModal
    .modal-dialog{:role => "document"}
      .modal-content
        .modal-header
          %button.close{'data-dismiss' => 'modal', 'aria-label' => 'Close'}
          %h4.modal-title Say something nice...
        .modal-body
          = form_for [current_user, @group.wall, Post.new] do |f|
            = f.text_area :text, class: 'form-control'
            .modal-footer
              .btn.btn-secondary{'data-dismiss' => 'modal'} Close
              = f.submit 'Post', :class => 'btn btn-primary'
- else
  .alert.alert-warning You have to subscribe to see this discussion.