config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { sessions: "user/sessions", registration: "user/registrations" }

  root 'profiles#index'

  resources :users do
		resources :groups do
      resources :subscriptions, only: [:create]
    end
    resources :profiles
    resources :walls, only: [:show] do
      resources :posts, only: [:create, :show] do
        resources :comments, only: [:create, :index]
      end
    end
    resources :friendships, only: [:create, :destroy]
    resources :feed_histories, only: [:show]
  end

  resources :groups, only: [:show, :destroy]
  resources :tags, only: [:index]

  patch 'friendships/read_requests' => 'friendships#read_requests'
  patch 'friendships/accept_friendship/:id' => 'friendships#accept_friendship'
  patch 'friendships/decline_friendship/:id' => 'friendships#decline_friendship'
  patch 'notifications/read_notifications/' => 'notifications#read_notifications'
  post  'posts/like' => 'posts#like'
  post  'comments/like' => 'comments#like'
  get 'comments/check_for_like' => 'comments#check_for_like'
  get 'users/:user_id/feed_histories/:id/sort_by_date' => 'feed_histories#sort_by_date'
  get 'users/:user_id/feed_histories/:id/sort_by_recommended' => 'feed_histories#sort_by_recommended'
  delete 'users/:user_id/groups/:group_id/subscriptions' => 'subscriptions#delete', as: :destroy_subscription

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates :text, length: { minimum: 2 }
  belongs_to :user
  belongs_to :post
  has_many :user_likes_posts, :as => :likeable
  has_many :users, :through => :user_likes_posts
  has_one :notification, :as => :notifiable
end

app/models/feed.rb
class Feed < ActiveRecord::Base
  belongs_to :user
  has_one :feed_history

  accepts_nested_attributes_for :feed_history,
    :reject_if => :all_blank,
    :allow_destroy => true
end

app/models/feed_history.rb
class FeedHistory < ActiveRecord::Base
  belongs_to :feed
  has_many :feed_history_has_posts
  has_many :posts, through: :feed_history_has_posts
end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
  belongs_to :user
  belongs_to :friend, :class_name => "User"
end

app/models/group.rb
class Group < ActiveRecord::Base
	belongs_to :admin, class_name: 'User'
	has_many :subscriptions
	has_many :users, :through => :subscriptions
	has_one :wall, as: :walled
  
  has_many :groups_have_tags
  has_many :tags, :through => :groups_have_tags
end

app/models/groups_have_tag.rb
class GroupsHaveTag < ActiveRecord::Base
  belongs_to :group
  belongs_to :tag
end

app/models/notification.rb
class Notification < ActiveRecord::Base
  belongs_to :user
  belongs_to :actor, :class_name => "User"
  belongs_to :notifiable, polymorphic: true
  #  Notification.create(:user_id => 13, :actor_id => 12, :notifiable_id => 7, :notifiable_type => 'Post', :message_type => 0, :seen => false)
end

app/models/post.rb
class Post < ActiveRecord::Base
  validates :text, length: { minimum: 2 }
  belongs_to :wall
  belongs_to :user
  has_many :feed_history_has_posts
  has_many :feed_histories, through: :feed_history_has_post
  has_many :comments
  has_many :user_likes_posts, :as => :likeable
  has_many :users, :through => :user_likes_posts
  has_one :notification, :as => :notifiable
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
  mount_uploader :avatar, AvatarUploader
  validates :first_name, presence: true
  validates :last_name, presence: true
end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
	belongs_to :user
	belongs_to :group
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :groups_have_tags
  has_many :groups, :through => :groups_have_tags
	
	has_many :user_interests
	has_many :users, :through => :user_interests
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  has_one :wall, as: :walled
  has_many :posts
  has_one :profile
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
  has_many :friendships
  has_many :friends, :through => :friendships
  has_many :user_likes_posts
  has_many :post_likes, :through => :user_likes_posts, :source => :likeable, :source_type => 'Post'
  has_many :comment_likes, :through => :user_likes_posts, :source => :likeable, :source_type => 'Comment'
  has_many :inverse_friendships, :class_name => "Friendship", :foreign_key => "friend_id"
  has_many :inverse_friends, :through => :inverse_friendships, :source => :user
  has_one :feed
  has_one :feed_history, through: :feed
  has_many :comments
  has_one :notification
  has_one :user_friends_preferences
	
	has_many :owned_groups, foreign_key: :admin_id, class_name: 'Group'
	has_many :subscriptions
	has_many :groups, :through => :subscriptions
	
	has_many :user_interests
	has_many :tags, :through => :user_interests
	

  accepts_nested_attributes_for :feed_history,
    :reject_if => :all_blank,
    :allow_destroy => true
end

app/models/user_interest.rb
class UserInterest < ActiveRecord::Base
  belongs_to :user
  belongs_to :tag
end

app/models/user_likes_post.rb
class UserLikesPost < ActiveRecord::Base
  belongs_to :user
  belongs_to :likeable, :polymorphic => true
end

app/models/user_popularity.rb
class UserPopularity < ActiveRecord::Base
  belongs_to :user
end

app/models/wall.rb
class Wall < ActiveRecord::Base
  has_many :posts
  belongs_to :walled, polymorphic: true
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/walls_helper.rb
module WallsHelper
end

app/views/layouts/_comments.html.haml
.row
  .col-md-2
    - if current_user.post_likes.where(:id => post.id).blank?
      .btn.btn-link.post_like_button{:data => { post_id: post.id, likes_count: UserLikesPost.where("likeable_id" => post.id).count.to_s}}
        = "Like (" + UserLikesPost.where("likeable_id" => post.id).count.to_s + ")"
    - else
      .btn.btn-link
        = "Liked! (" + UserLikesPost.where("likeable_id" => post.id).count.to_s + ")"
  .col-md-2
    .btn.btn-link{"data-toggle" => "collapse", "data-target" => "#uniqueId" + unique_id }
      - if !post.comments.blank?
        = "Comment (" + post.comments.count.to_s + ")"
      - else
        Comment

  .col-md-9
.collapse{:id => "uniqueId" + unique_id}
  = react_component('CommentsView',{count: post.comments.count,
                                    user_id: current_user.id,
                                    wall_id: post.wall.id,
                                    post_id: post.id})
  /
    - post.comments.each do |comment|
      .row
        .col-md-1
        .col-md-10
          .panel.panel-default
            .panel-heading
              .row
                .col-md-1
                  %img{:src => comment.user.profile.avatar, :alt => "avatar image", :width => 25, :height => 25 }
                .col-md-11
                  = comment.user.profile.first_name + " said:"
            .panel-body
              = comment.text
              .row
                .col-md-1
                  - if current_user.comment_likes.where(:id => comment.id).blank?
                    .btn.btn-link.comment_like_button.comment_margin_fix{:data => { comment_id: comment.id, likes_count: UserLikesPost.where("likeable_id" => comment.id).count.to_s}}
                      = "Like (" + UserLikesPost.where("likeable_id" => comment.id).count.to_s + ")"
                  - else
                    .btn.btn-link.comment_margin_fix
                      = "Liked! (" + UserLikesPost.where("likeable_id" => comment.id).count.to_s + ")"
                .col-md-11
        .col-md-1
/
  .row
    .col-md-1
    .col-md-10
      = form_for [current_user, post.wall, post, Comment.new], :class => "margin-fix" do |f|
        .input-group
          = f.text_field :text, { :class => "form-control", :placeholder => "Post a comment..." }
          %span.input-group-btn
            = f.submit "Post Comment", :class => "btn btn-default"
    .col-md-1
  .row
    .col-md-12
      &nbsp

app/views/layouts/_friend_request.html.haml
%li
  .panel.panel-default
    .panel-body
      = link_to request.user.profile.first_name.to_s + " has sent you a friend request!", user_profile_path(request.user.id, request.user.profile.id), :class => "request-link pull-left"
      = link_to "Decline", { :controller => :friendships, :action => :decline_friendship, :id => request.id}, :class => "btn btn-default pull-right", :method => :patch

app/views/layouts/_group.html.haml
.row.feed_title
  .col-md-8
    .media
      .media-left.media-middle
        .a{:href => "#"}
          %img.media-object{:src => group.imageSource, :witdh => 64, :height => 64 }
      .media-body
        %h3.media-heading.title_fix
          = link_to group.title, user_group_path(current_user.id, group.id)
        %p
          %small
            = group.short_description
  .col-md-4
%br

app/views/layouts/_main_link.html.haml
- if is_link_available(name)
  %li{:class => get_active_link(controller, current_user.send(name)) + " main-link"}
    = link_to "Your " + name, send("user_" + path + "_path", current_user.id, current_user.send(model).id), :method => :get, :class => "main-link"

app/views/layouts/_notification.html.haml
%li.list-group-item
	- if notification.notifiable_type == 'Post'
		- case notification.message_type
		- when 0 then
			= link_to notification.actor.profile.first_name + " has liked your post!", user_wall_post_path(notification.notifiable.wall.walled.id, notification.notifiable.wall.id, notification.notifiable.id)
		- when 1 then
			= link_to notification.actor.profile.first_name + " has posted on your wall!", user_wall_post_path(notification.notifiable.wall.walled.id, notification.notifiable.wall.id, notification.notifiable.id)
		- when 2 then
			= link_to notification.actor.profile.first_name + " has posted on " + notification.notifiable.wall.walled.title, user_wall_post_path(notification.notifiable.wall.walled.id, notification.notifiable.wall.id, notification.notifiable.id)
	- else
		- case notification.message_type
		- when 1 then
			= link_to notification.actor.profile.first_name + " has liked your comment!", user_wall_post_path(notification.notifiable.post.wall.walled.id, notification.notifiable.post.wall.id, notification.notifiable.post.id)
		- when 0 then
			= link_to notification.actor.profile.first_name + " has commented on your post!", user_wall_post_path(notification.notifiable.post.wall.walled.id, notification.notifiable.post.wall.id, notification.notifiable.post.id)

app/views/layouts/_post.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <div class="row">
      <div class="col-md-1">
        <div class="thumbnail">
          <img src=<%= post.user.profile.avatar %> alt="avatar image" width=50 height=50>
        </div>
      </div>
      <div class="col-md-11">
        <h3 class="panel-title">
          <%- if current_user.id == post.user.id %>
            You said:
          <% else %>
           <%= post.user.profile.first_name %> said:
          <% end %>
         </h3>
      </div>
    </div>
  </div>
  <div class="panel-body">
    <p><%= post.text %> </p>
  </div>
</div>

app/views/layouts/_post.html.haml
.row
	.col-md-3
	.col-md-6
		.panel.panel-default
			.panel-heading
				.row
					.col-md-2
						.thumbnail
							%img{:src => post.user.profile.avatar, :alt => "avatar image", :width => 50, :height => 50 }
					.col-md-7
						- if current_user.id == post.user.id
							%h3.panel-title You said:
						- else
							%h3.panel-title= post.user.profile.first_name + " said"
					.col-md-3
						- if current_user.wall.id == post.wall.id
							%h6 on your wall
						- elsif post.wall.walled.is_a?(User)
							%h6= "on " + post.wall.walled.profile.last_name + "'s wall"
						- else
							%h6= "on " + post.wall.walled.title

			.panel-body
				%p= post.text
				= render "layouts/comments", :post => post, :unique_id => post.id.to_s
	.col-md-3
/
	= form_for [current_user, post.wall, post, Comment.new], :class => "margin-fix" do |f|
		.input-group
		= f.text_field :text, { :class => "form-control", :placeholder => "Post a comment..." }
		%span.input-group-btn
		= f.submit "Post Comment", :class => "btn btn-default"

app/views/layouts/_userPartial.html.haml
.row
  .col-md-1
  .col-md-10
    .panel.panel-default
      .panel-body
        .row
          .col-md-4
            .thumbnail
              %img{:src => user.profile.avatar, :alt => "avatar image", :width => 50, :height => 50 }
          .col-md-8
            = link_to user.profile.first_name.to_s + " " + user.profile.last_name.to_s, user_wall_path(user.id, user.wall.id)
  .col-md-1

app/views/layouts/application.html.haml
%html
  %head
    %title Webinator
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    %link{:rel => :stylesheet, :type => :"text/css", :href => 'https://fonts.googleapis.com/css?family=Days+One'}
    = csrf_meta_tags

%body
  %nav.navbar.navbar-full.cool-bg
    .container-fluid
      / Brand and toggle get grouped for better mobile display
      .navbar-header
        %button{:type => "button", :class => "navbar-toggle collapsed", "data-toggle" => "collapse", "data-target" => "#bs-example-navbar-collapse-1", "aria-expanded" => false}
          %span.sr-only Toggle Navigation
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        %a.navbar-brand.little-padding-bottom
          %p.logo W

      / Collect the nav links, forms, and other content for toggling
      .collapse.navbar-collapse#bs-example-navbar-collapse-1
        %ul.nav.navbar-nav
          / Profile link
          =render "layouts/main_link", :name => "profile", :controller => "profiles", :model => "profile", :path => "profile"

          / Wall link
          =render "layouts/main_link", :name => "wall", :controller => "walls", :model => "wall", :path => "wall"

          / Feed link
          =render "layouts/main_link", :name => "feed", :controller => "feed_histories", :model => "feed_history", :path => "feed_history"
					
          -# Groups link
          - unless current_user.nil?
            - if params[:controller] == "groups"
              %li{ :class => "nav-bar-link-active"}
                = link_to "Your groups", user_groups_path(current_user.id), :method => :get, :class => "main-link"
            - else
              %li{ :class => "main-link"}
                = link_to "Your groups", user_groups_path(current_user.id), :method => :get, :class => "main-link"

          / user search
          - if current_user
            = form_tag(users_path,method: "get", class: "navbar-form navbar-left") do
              .input-group
                %span.input-group-btn
                  = submit_tag("Search", class: "btn btn-default")
                = text_field_tag :q, nil, class: 'form-control'

            %li.btn.btn-lg.dropdown#notifications-widget{:data => { notifications: new_notifications}}
              .dropdown-toggle.drop-fix{"data-toggle" => "dropdown", :role => :button, "aria-haspopup" => :true, "aria-expanded" => :false}
              %span.glyphicon.glyphicon-globe
              - if @nots_count > 0
                %span.badge.badge-super#notifications-badge
                  = @nots_count
              %ul.dropdown-menu.textfull.list-group
                - if get_notifications.blank?
                  %li.list-group-item
                    You have no notifications!
                - else
                  - get_notifications.each do |notification|
                    = render "layouts/notification", :notification => notification


            %li.btn.btn-lg.dropdown#requests-widget{:data => { requests: new_requests}}
              .dropdown-toggle.drop-fix{"data-toggle" => "dropdown", :role => :button, "aria-haspopup" => :true, "aria-expanded" => :false}
              %span.glyphicon.glyphicon-user
              - if @reqs_count > 0
                %span.badge.badge-super#requests-badge
                  = @reqs_count
              %ul.dropdown-menu.textfull.list-group
                - if pending_friend_requests.blank?
                  %li.list-group-item
                    You have no more friend requests!
                - else
                  - pending_friend_requests.each do |request|
                    = render "layouts/friend_request", :request => request
							

            %li.btn.btn-lg.dropdown
              .dropdown-toggle.drop-fix{"data-toggle" => "dropdown", :role => :button, "aria-haspopup" => :true, "aria-expanded" => :false}
              %span.glyphicon.glyphicon-cog
              %ul.dropdown-menu
                %li#editAccountListItem
                  = link_to 'Edit Account', edit_user_registration_path(current_user)


        %ul.nav.navbar-nav.navbar-right
          - if current_user
            %li= link_to "Sign out!", destroy_user_session_path, :class => "main-link"

  - if notice
    %p.alert.alert-success= notice
  - if alert
    %p.alert.alert-danger= alert


  = yield